### ISSUE TITLE
shortcuts don't work

### ISSUE THREAD

**Issue by Aaquarium** [AndyLobjois/BRC-MeshRemix#10]

**Comment by AndyLobjois** [comment]
I don't know if you closed this issue by mistake or because you find the answer yourself.

Just in case, here is the common issues people have :
## Wrong Install
You should check the BepInEx console to see if DripRemix stuff is loaded. If it's not you should check the [tutorial](https://thunderstore.io/c/bomb-rush-cyberfunk/p/AndyLobjois/DripRemix/) for how to install stuff correctly.
> Note : ModdingFolder is created by DripRemix in Steam/steamapps/common/BRC, NOT in BepInEx/Plugin folder. Please, read carefully, and compare with my Examples.zip

## Wrong Shortcuts
Don't forget to hold the keys while doing the combination.
> Example : Hold G + PageDown for scrolling down Gear skins.

## Know How Your Keyboard Works
If you can't press PageUp/PageDown/Home/End or have difficulties, you can rebind the keys from BepInEx/config/dripremix.cfg
> Please, refer to the correct spelling of the key, you have a list right above in the config file, case sensitive too.
